# Configuration values in this file are used by all profiles,
# unless overridden in the profile-specific configuration files
# or via an environment variable.
server:
  ip: "0.0.0.0"
  port: 8090
  graceful_shutdown_timeout: 1 minute
session:
  ttl: 24 hours
database:
  url: "mysql://root:password@localhost:3306/session_demo"
greet:
  use_name: true
  greeting_message: "Thank you for choosing Pavex with MySQL sessions for your project!"
